### PR TITLE
0.19 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I would have a PR to add here, but I have to first work on it. Fixing the docs.rs builds due to workspace changes

**Comment by sdroege** [comment]
I was going to make a bugfix release today because multiple people ran into the `syn` version issue. What's the ETA for your fix?

**Comment by bilelmoussaoui** [comment]
> I was going to make a bugfix release today because multiple people ran into the `syn` version issue. What's the ETA for your fix?

Hopefully this evening, otherwise

**Comment by bilelmoussaoui** [comment]
Another commit to backport https://github.com/gtk-rs/gtk-rs-core/pull/1310

**Comment by sdroege** [comment]
> Hopefully this evening, otherwise

Ok, I'll be busy with other things until tomorrow afternoon anyway now :)

**Comment by sdroege** [comment]
@bilelmoussaoui Added your docs.rs commit here too. Anything else missing?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Added your docs.rs commit here too. Anything else missing?

Nothing comes to mind now, thanks a lot!

**Review by bilelmoussaoui — APPROVED** [review]

**Pull request merged**
