### PR TITLE
glib: impl ToGlibPtr for HashMap<&str, Object>

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Needed for https://github.com/gtk-rs/gtk4-rs/issues/190

### CODE REVIEW

**Review by GuillaumeGomez — DISMISSED** [review]

**Comment by bilelmoussaoui** [comment]
I wonder why the CI wasn't triggered?

**Comment by GuillaumeGomez** [comment]
Hum weird. Still saying that the workflow is starting.

**Review by sdroege — COMMENTED** [review]
The CI is failing on Windows, that can be easily fixed.

Otherwise this looks ok to me.

**Comment by bilelmoussaoui** [comment]
This one isn't actually useful to me anymore. I don't believe it makes sense to have it as i don't see why someone would need it :)

**Pull request closed without merging**
