### PR TITLE
glib: Fix FromValue impls for &Boxed, &Shared and &Object

### PR DESCRIPTION
**Pull request by sdroege**
This time it's hopefully all correct, for real. Third time!

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Can you add tests where the `assert` is triggered please?

**Comment by sdroege** [comment]
Which assertion? These assertion in the changes here can only be hit if we get invalid data from C

**Comment by sdroege** [comment]
FWIW the old tests covered the bugs fixed here already. You just had to run them in valgrind.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Well, let's hope they'll never get triggered then.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
> Well, let's hope they'll never get triggered then.

If they get triggered we can report a bug to the C library, so that's useful :) It will be clearer with the assertion than if it blows up later in completely strange ways.

**Pull request merged**
