### PR TITLE
Add ValueDelegate macro

### LINKED ISSUE #983: [FEATURE REQUEST] Newtype support for `#[property]`
I have a newtype over f64:
```rust
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ScaleRequest {
    FitToAllocation,
    Set(f64),
}
```
It maps one-to-one to f64 (0. maps to the first item, others map to the second item). I'd like to use it with the properties macro. For GObject it should appear as an f64 property.

Currently this seems to require implementing `HasParamSpec`, `ToValue`, `From<ScaleRequest> for Value` (for some reason?) and `FromValue`, the last of which requires unsafe code:
```rust
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ScaleRequest {
    FitToAllocation,
    Set(f64),
}

impl From<f64> for ScaleRequest {
    fn from(value: f64) -> Self {
        if value == 0. {
            ScaleRequest::FitToAllocation
        } else {
            ScaleRequest::Set(value.clamp(0., 10.))
        }
    }
}

impl glib::HasParamSpec for ScaleRequest {
    type ParamSpec = glib::ParamSpecDouble;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecDoubleBuilder;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl From<ScaleRequest> for glib::Value {
    fn from(value: ScaleRequest) -> Self {
        value.to_value()
    }
}

impl glib::ToValue for ScaleRequest {
    fn to_value(&self) -> glib::Value {
        match *self {
            ScaleRequest::FitToAllocation => 0.,
            ScaleRequest::Set(scale) => scale,
        }
        .to_value()
    }

    fn value_type(&self) -> glib::Type {
        f64::static_type()
    }
}

unsafe impl<'a> glib::value::FromValue<'a> for ScaleRequest {
    type Checker = glib::value::GenericValueTypeChecker<f64>;

    unsafe fn from_value(value: &'a glib::Value) -> Self {
        f64::from_value(value).into()
    }
}
```

Would be great if this could be representable without unsafe code with some kind of pair of `From<f64> for T` + `From<T> for f64`.

It's also worth noting that I could instead implement `Property` with `Value = f64` and custom get and set returning `f64`. However, that would result in my Rust type having getter and setter working with `f64` instead of the real type, which is not as nice.

### PR DESCRIPTION
**Pull request by ranfdev**
closes #983 

It works pretty well I'd say.

Should I add support for generics?

### CODE REVIEW

**Comment by ranfdev** [comment]
Added support to make the newtype `nullable`, implementing `ToValueOptional`.
I won't add support for generics, unless requested.
Done

**Comment by pbor** [comment]
The code itself looks good to me, though given that this is a new API etc, before merging I would prefer to get a thumbs-up from someone who had approval permission for more than a couple of days :)

In the mean time let me bring up some bikeshedding: which alternatives have we considered to the `ValueDelegate` name? I do not find it super clear... how about `ValueRepresentation` or `ValueRepr` ?

**Comment by pbor** [comment]
Also, if `nullable` is specified, should we accept/use `TryFrom` and set `None` in case of error?

**Comment by ranfdev** [comment]
> naming
`ValueRepresentation` is a bit too long. `ValueRepr` would be ok, but in any case I think `ValueDelegate` is clearer. The macro doesn't provide a _full_ representation. The representation is _delegated_ to the chosen type. GLib can't distinguish `MyInt(i32)` and an `i32`. So `MyInt(i32)` doesn't have a full representation. That would require registering another glib type.

> should we accept/use `TryFrom` and set `None` in case of error?

No, because that would silently ignore the error. We would need a specific `Checker` inside the `ToValue` trait to handle the conversion and provide a useful error. I agree this can be useful.

**Review by pbor — DISMISSED** [review]
As mentioned, this looks good to me, but let's wait for other reviews as well before adding new API

**Comment by ranfdev** [comment]
@sdroege we would like a thumbs up before merging a new API :)

**Review by sdroege — DISMISSED** [review]

**Comment by sdroege** [comment]
Seems good to me, please merge after solving the conflicts :)

**Comment by sdroege** [comment]
So let's get this in now? @pbor ?

**Comment by ranfdev** [comment]
I wanted to merge it, I just needed a review to do so

**Review by sdroege — APPROVED** [review]

**Pull request merged**
