### PR TITLE
glib: Allow using other error types and value type checkers for …

### PR DESCRIPTION
**Pull request by sdroege**
…optional values

### CODE REVIEW

**Comment by jf2048** [comment]
Looks like a prereq for #502

**Comment by sdroege** [comment]
> Looks like an additional bit for #502

In what sense?

**Comment by jf2048** [comment]
I think we want to check those (and other fundamental types) when using `FromValue`

**Comment by sdroege** [comment]
Did you link to the wrong issue? Or I'm misunderstanding what you want to do :) Can you give some more details?

**Comment by sdroege** [comment]
@GuillaumeGomez @bilelmoussaoui This one is ready now, I made sure things are working correctly in GStreamer and the new feature can actually be used properly.

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
