### PR TITLE
Update crates version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Forgot to push this one. :-°

### CODE REVIEW

**Comment by sdroege** [comment]
> You broke the CI :P https://github.com/gtk-rs/gtk-rs-core/pull/102/checks?check_run_id=2693216777

Because you updated/changed the gir submodule but didn't regenerate

**Comment by sdroege** [comment]
(and that should be in a separate PR I guess)

**Comment by GuillaumeGomez** [comment]
Oh crap, I updated the gir submodule...

**Comment by GuillaumeGomez** [comment]
Fixed. \o/

**Review by sdroege — APPROVED** [review]

**Pull request merged**
