### PR TITLE
glib: Mark various Variant getter functions correctly as (transfer fu…

### PR DESCRIPTION
**Pull request by sdroege**
…ll) in their return value

Fixes a couple of memory leaks.

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez Before you complain, the existing tests already cover that but apparently nobody runs them through valgrind except for me every now and then :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Could be interesting to run them through valgrind in the CI then. :p (Also, I never complain on fixes!)

**Comment by bilelmoussaoui** [comment]
> Could be interesting to run them through valgrind in the CI then. :p (Also, I never complain on fixes!)

Can you open an issue so we can figure out whether it's possible to do so?

**Comment by GuillaumeGomez** [comment]
I do it for another project of mine. Opening the issue.

**Pull request merged**
