### PR TITLE
glib: add missing doc-aliases to Type

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I'm surprised that the CI didn't complain about these missing ones...

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Yay, new clippy warnings in beta.

**Comment by sdroege** [comment]
> I'm surprised that the CI didn't complain about these missing ones...

@GuillaumeGomez The checker is only looking at functions, not constants.

**Comment by bilelmoussaoui** [comment]
> Yay, new clippy warnings in beta.

Lets get this one in and figure out the new warnings in a different PR?

**Comment by sdroege** [comment]
Sure. That's why, for GStreamer, updating to a new release is manually so that the CI is not just broken automatically but can be fixed at the same time as the update happens :)

**Comment by GuillaumeGomez** [comment]
> > I'm surprised that the CI didn't complain about these missing ones...
> 
> @GuillaumeGomez The checker is only looking at functions, not constants.

Well it should, I'll send a PR for that. :3

**Pull request merged**
