### PR TITLE
Structured logging backport

### PR DESCRIPTION
**Pull request by mbiggio**

### CODE REVIEW

**Comment by sdroege** [comment]
@mbiggio Can you cherry pick the individual commits you want to backport?

**Review by sdroege — APPROVED** [review]
Seems ok to backport to me

**Comment by sdroege** [comment]
Unfortunately the `gstr!` macro requires a newer Rust version: https://github.com/gtk-rs/gtk-rs-core/runs/5535196508?check_suite_focus=true . So that's not acceptable. Can we do without for the backport?

**Comment by mbiggio** [comment]
> Unfortunately the `gstr!` macro requires a newer Rust version: https://github.com/gtk-rs/gtk-rs-core/runs/5535196508?check_suite_focus=true . So that's not acceptable. Can we do without for the backport?

The problem comes from this assert:
https://github.com/gtk-rs/gtk-rs-core/blob/master/glib/src/gstring.rs#L46
that is not allowed in a `const` function in rust 1.56.0.

Maybe we can drop the assert? - the necessary preconditions are listed in the comments above the functions, so in a sense the caller is supposed to make sure they are satisfied, but this opens the door to UB ...

**Comment by pbor** [comment]
> The problem comes from this assert: https://github.com/gtk-rs/gtk-rs-core/blob/master/glib/src/gstring.rs#L46 that is not allowed in a `const` function in rust 1.56.0.
> 
> Maybe we can drop the assert? - the necessary preconditions are listed in the comments above the functions, so in a sense the caller is supposed to make sure they are satisfied, but this opens the door to UB ...

The function is called `unchecked`, so imho dropping the assert is ok

**Comment by sdroege** [comment]
@jf2048 What do you think?

**Comment by jf2048** [comment]
Yes, you can take that assert out, it was copied from `CStr` nightly and it was only added last month.

**Pull request merged**
