### PR TITLE
glib-macros: Port clone failure tests to trybuild2

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This is a simplification of #578.

cc @jf2048

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
CI is failing because of clippy lints. Sending a PR to fix them...

**Comment by jf2048** [comment]
LGTM, if we take this approach I was also thinking about using `quote::quote!` instead of strings

**Comment by GuillaumeGomez** [comment]
You lost me there. Which strings are you referring to?

**Comment by GuillaumeGomez** [comment]
And rebased. Let's see if the CI is happier.

**Comment by GuillaumeGomez** [comment]
CI passed! \o/

**Comment by jf2048** [comment]
Like:
```rust
   (quote! { clone!( => move || {}) },
     "If you have nothing to clone, no need to use this macro!"),
    (quote! { clone!(|| {}) },
     "If you have nothing to clone, no need to use this macro!"),
    (quote! { clone!(|a, b| {}) },
     "If you have nothing to clone, no need to use this macro!"),
```
etc, just to make it clearer this is rust syntax

**Comment by sdroege** [comment]
It gives you proper tooling support for writing more than a single line of code in there.

**Comment by GuillaumeGomez** [comment]
You can write more than one already. I don't see why using `quote` improves anything.

**Comment by GuillaumeGomez** [comment]
There is syntax highlighting in `quote`? Also, you can write that in a real rust file if you prefer.

**Comment by sdroege** [comment]
What's the plan here?

**Comment by GuillaumeGomez** [comment]
For me it's ready as is.

**Pull request merged**
