### PR TITLE
pango: add missing v1_50 feature

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
cc @sdroege

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Isn't it tested in the CI?

**Comment by bilelmoussaoui** [comment]
> Isn't it tested in the CI?

No, the CI image doesn't have a newer pango. It will be tested in gtk4-rs's CI indirectly

**Comment by GuillaumeGomez** [comment]
Better than nothing. Indirect testing is a bit weird but whatever. :)

Thanks!

**Comment by bilelmoussaoui** [comment]
It will soon be tested, I just need to figure out how to handle this whole docker image for gtk-rs-core.

**Comment by sdroege** [comment]
Also covered by the gstreamer-rs CI AFAICS

**Pull request merged**
