### PR TITLE
Deduplicate metadata for structured logging

### LINKED ISSUE #1537: [BUG] GLib structured logger duplicates CODE_FILE, CODE_LINE, and CODE_FUNC
**Bug description**

When `GLibLoggerFormat::Structured` is used, the `Log::log` implementation of `GLibLogger` calls `GlibLogger::write_log_structured`, passing the log record's file, line, and module_path as line, file, and function name respectively.

`GlibLogger::write_log_structured` then calls `log_structured!`, passing the line, file, and function name as the `CODE_FILE`, `CODE_LINE` and `CODE_FUNC` fields respectively.

However, the `log_structured!` then _again_ adds `CODE_FILE`, `CODE_LINE`, and `CODE_FUNC`, using the values of `file!()`, `line!()`, and a custom `function_name!()` respectively.

Hence, any log event from the structured logger ends up with duplicated `CODE_*` fields, where the duplicates always reference the `GLibLogger::write_log_structured` call site.

Is this intended behaviour?

### PR DESCRIPTION
**Pull request by swsnr**
Closes #1537

### CODE REVIEW

**Comment by swsnr** [comment]
@sdroege This adds a test for the log impl and removes the duplicated metadata by avoiding the `log_structured!` macro.

**Comment by swsnr** [comment]
@sdroege I'd like to point out that changed the pipeline to hopefully include the `log` feature so as to run the new test on Github actions.  However, since the pipeline didn't pass in the first place (it's even broken on master), and is somewhat complex, the change to the Github workflow is more of an educated guess than actually understanding what I did there :innocent:

**Comment by sdroege** [comment]
> since the pipeline didn't pass in the first place (it's even broken on master)

Yeah packages are automatically updated there and one update requires changes in the tests. I hope to get to fixing this some time this week. Sorry for the trouble!

**Comment by swsnr** [comment]
@sdroege No worries, didn't affect me much, as I can just run tests locally.  Just wanted to point the one part of this PR I'm not entirely sure about :innocent:

**Comment by sdroege** [comment]
It looks correct. I'll fix it if it isn't :)

**Comment by swsnr** [comment]
Thanks for merging :pray:

**Pull request merged**
