### PR TITLE
Support `default = ...` in the properties macro

### PR DESCRIPTION
**Pull request by pbor**
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/957

### CODE REVIEW

**Comment by pbor** [comment]
This does not work yet because the test does not pass, but I am confused on the reason why: the macro generates the corrected thing:

```
                    <<RefCell<
                        String,
                    > as glib::Property>::Value as glib::HasParamSpec>::param_spec_builder()(
                            "with-default",
                        )
                        .readwrite()
                        .default_value("hello")
                        .build(),
```

However getting the property still returns `""`... is there a bug somewhere else that ignores the default value?

**Comment by pbor** [comment]
As confusing as it is, I think that was expected, since the prop default is just what is set in the glib type system, but it is not automatically used when initializing an instance. I changed the unit test.

cc @ranfdev

**Comment by sdroege** [comment]
CC @ranfdev

**Comment by ranfdev** [comment]
Looks good to me

**Review by sdroege — APPROVED** [review]

**Review by sdroege — APPROVED** [review]

**Pull request merged**
