### PR TITLE
gio: mark `content_type_guess` parameter as filename

### PR DESCRIPTION
**Pull request by euclio**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Ideally this needs to be fixed upstream

**Comment by euclio** [comment]
I see, what would that fix look like?

**Comment by sdroege** [comment]
Like here: https://gitlab.gnome.org/GNOME/glib/-/blob/62a88d9f38c77f140fb7f6d714fb4445277ce5e4/glib/gfileutils.c#L210

**Review by sdroege — APPROVED** [review]

**Comment by euclio** [comment]
Upstream MR: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2411

**Pull request merged**
