### PR TITLE
0.20 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Once this passes, I'll get out a round of bugfix releases for gtk-rs-core later. gtk4-rs tomorrow, gstreamer-rs Wednesday, gst-plugins-rs Thursday.

**Comment by bilelmoussaoui** [comment]
Is the part where we ignore the clippy warning still needed with the latest gir changes?

**Comment by sdroege** [comment]
Yes

**Comment by sdroege** [comment]
In 0.20 only, in main it should be fine

**Pull request merged**
