### PR TITLE
0.20 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Any reason for not backporting the new dbus stuff as well? They are not breaking API changes and would make the contributior happy about it :)

**Comment by sdroege** [comment]
I wanted to let it settle for one more round of bugfix releases in case someone wants to improve the API

**Comment by sdroege** [comment]
gir files updated here now

**Comment by swsnr** [comment]
@sdroege As far as I am concerned you could also mark these DBus things as experimental and exempt them from the usual semver guarantees.

If someone comes along and makes substantial improvements to these I'd be happy to deal with the resulting breakage :sweat_smile:

**Comment by sdroege** [comment]
Ok, I'll include it in the next round :)

**Pull request merged**
