### PR TITLE
gio: Add local variant for connect_cancelled

### PR DESCRIPTION
**Pull request by SeaDve**
I'm not sure if I got it right

### CODE REVIEW

**Comment by sdroege** [comment]
We discussed this when adding the non-local variants and didn't consider adding it because why would anybody need that :) What's your use-case?

**Review by sdroege — APPROVED** [review]

**Comment by SeaDve** [comment]
> We discussed this when adding the non-local variants and didn't consider adding it because why would anybody need that :) What's your use-case?

I use it currently to update some GTK UI state directly through the cancelled callback

**Comment by sdroege** [comment]
How do you make sure that cancellation only happens from the main thread?

**Comment by SeaDve** [comment]
I'm not sure how to explain it correctly, but here is my current usage (used a custom cancellable there):

https://github.com/SeaDve/Mousai/blob/53f2afbadbb89151c7afac120fa45cae3d20f12a/src/recognizer/mod.rs#L199

It was made sure that the cancellation happens at the main thread because it was not sent at all to other threads.

**Pull request merged**
