### PR TITLE
gio: remove Send + Sync requirements from DBusConnection::register_ob…

### PR DESCRIPTION
**Pull request by pbor**
…ject

glib documentation says:
"Calls to functions in vtable (and user_data_free_func ) will happen in the thread-default main context of the thread you are calling this method from."

### CODE REVIEW

**Review by sdroege — DISMISSED** [review]
Did you check if this is the only place in GDbus?

**Comment by pbor** [comment]
There are other places, eg `g_bus_own_name_with_closures` but there the documentation is not explicit about where they run

**Comment by sdroege** [comment]
All GDbus callbacks should run from the main thread I think? Can you check that and update it all at once so we don't have to do it one by one?

**Comment by pbor** [comment]
Added the other functions.

This fixes https://github.com/gtk-rs/gtk-rs-core/issues/263

**Review by sdroege — APPROVED** [review]

**Pull request merged**
