### PR TITLE
Regenerate with latest gir

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
See gtk-rs/gir#1266 & gtk-rs/gir#1264

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please provide link to gir PR and update your title so it say what the regen is about.

**Review by sdroege — DISMISSED** [review]

**Comment by bilelmoussaoui** [comment]
> Please provide link to gir PR and update your title so it say what the regen is about.

I updated the commit message, it contains changes from multiple recent gir changes; so it's not specific to the impl blocks

**Review by sdroege — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Then link to the various gir PRs involved please.

**Comment by bilelmoussaoui** [comment]
Sure, updated the PR content

**Comment by GuillaumeGomez** [comment]
Thanks!

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
