### PR TITLE
Expose the type of pango::Attribute

### PR DESCRIPTION
**Pull request by jsparber**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I don't think we should actually be exposing AttrClass at all but rather uses it directly in Attribute?

**Comment by jsparber** [comment]
> I don't think we should actually be exposing AttrClass at all but rather uses it directly in Attribute?

I think it makes sense to move it to `Attribute::type_()`.

**Comment by sdroege** [comment]
Yeah, can you add it there? Having it also on the class is OK though

**Comment by jsparber** [comment]
> Yeah, can you add it there? Having it also on the class is OK though

done. :)

**Review by sdroege — APPROVED** [review]

**Pull request merged**
