### PR TITLE
Run clippy on beta

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by sdroege** [comment]
Do we only want to run on beta, or also on stable?

**Comment by GuillaumeGomez** [comment]
Hum... This is a good question. Generally clippy adds more lints, rarely remove them or change their default level, no?

**Comment by sdroege** [comment]
But it would probably be nice to also not have clippy warnings on current stable

**Comment by GuillaumeGomez** [comment]
I'll update the commits to check on both.

**Review by sdroege — APPROVED** [review]

**Pull request merged**
