### PR TITLE
glib: Merge variants of `wrapper!` as much as possible

### PR DESCRIPTION
**Pull request by ids1024**
Handling object wrappers with or without `@extends` and with or without `@implements` in one variant is problematic, since a comma between the two is necessary if and only if both are used.

But assuming no issues turn up, this should be a good improvement making this a fair bit simpler.

### CODE REVIEW

**Comment by sdroege** [comment]
Did you check if gtk3-rs, gtk4-rs and gstreamer-rs still build fine with this and end up with the same expanded code?

**Comment by ids1024** [comment]
Both seem to build fine. Not sure how best to compare the expanded code.

**Comment by sdroege** [comment]
> Not sure how best to compare the expanded code.

Good question. `cargo expand` and diffing might work?

**Comment by GuillaumeGomez** [comment]
Just like @sdroege said: please give us before/after expanded code (because reviewing changes to this macro is a bit complicated...).

**Comment by ids1024** [comment]
There seems to be no difference in the output of `cargo expand` for the `gtk` and `gtk4` crate. On `gtk-rs-examples`, `cargo expand` errors (https://github.com/dtolnay/cargo-expand/issues/105).

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Ok, the changes also look good to me so let's get it in then. We can take care of any fallout afterwards, but generally it should work fine :)

**Pull request merged**
