### PR TITLE
gio: require Send also for the source object

### PR DESCRIPTION
**Pull request by pbor**

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Seems good, but if you make it a generic parameter on `Task` too then you can also provide the correct target type in the `run_in_task` closure :)

**Comment by pbor** [comment]
Dunno... since you have to explicitly do `task: gio::LocalTask<i64>` etc in callbacks etc, having more generics that are often not used would be annoying imho

**Comment by sdroege** [comment]
True. I guess we can worry about that when someone needs it

**Comment by sdroege** [comment]
Needs a `cargo fmt` run

**Review by sdroege — APPROVED** [review]

**Pull request merged**
