### PR TITLE
Implement `FusedIterator` for various custom iterators

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by bilelmoussaoui — DISMISSED** [review]

**Comment by sdroege** [comment]
@bilelmoussaoui @GuillaumeGomez Any opinions on this? :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It extends the API so seems like a good idea to me.

**Comment by sdroege** [comment]
> It extends the API so seems like a good idea to me.

Not really. These functions have default implementations but we can implement them much more efficiently in our case.

**Comment by GuillaumeGomez** [comment]
Then it's even better!

**Pull request merged**
