### PR TITLE
glib-macros: main macro for simple async applications

### PR DESCRIPTION
**Pull request by BiagioFesta**
I am interested into https://github.com/gtk-rs/gtk-rs-core/issues/31.
I would like to contribute if/as I can.

This PR is more a request for comment, and it might go in that direction of having more ergonomic constructs for async code rust/glib.

It is deliberately inspired by https://docs.rs/tokio/latest/tokio/attr.main.html

### CODE REVIEW

**Comment by BiagioFesta** [comment]
Honestly, I did not think about that case. 

Maybe the macro can be expanded with `args` to build a wrapper for `gio::Application` too. Or maybe it is not worth it.

If any, please leave your suggestion.

Otherwise I think we can reject and close this PR.

**Comment by sdroege** [comment]
I think this needs some thinking for how to handle that or if that's possible at all.

**Comment by jf2048** [comment]
How about:

```rust
#[gio::main(
    app(
        class = "MyApplication",
        id = "org.example.MyApp",
        flags = "gio::ApplicationFlags::HANDLES_OPEN",
    )
)]
// leave fields blank to defaults to using gio::Application with empty flags
#[gio::main(app(id = "org.example.MyApp"))]
```

Would expand to this:

```rust
gio::prelude::ApplicationExtManual::run(
    &glib::Object::new::<MyApplication>(&[
        ("application-id", &"org.example.MyApp"),
        ("flags", &(gio::ApplicationFlags::HANDLES_OPEN)),
    ])
)
```

**Comment by sdroege** [comment]
How should we move forward here?

**Pull request closed without merging**
