### PR TITLE
glib: export Signal

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by sdroege** [comment]
Not sure this makes much sense. It's only relevant for subclasses and we intentionally don't re-export any subclass API from the crate root. Instead it's all re-exported into the `glib::subclass` module.

What's the problem with having it there?

**Comment by A6GibKm** [comment]
It is the only struct that I have to manually import as `glib::subclass::Signal`. Can't it be on glib::subclass::prelude either?

**Comment by bilelmoussaoui** [comment]
> It is the only struct that I have to manually import as `glib::subclass::Signal`. Can't it be on glib::subclass::prelude either?

Well you do that right now because you have to manually define signals, if there were a macro... you wouldn't need to do that :)

**Comment by sdroege** [comment]
> Can't it be on glib::subclass::prelude either?

No, only traits in preludes.

**Comment by A6GibKm** [comment]
Closing as there are good reasons not to merge this.

**Pull request closed without merging**
