### PR TITLE
Bump dockerfile to ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by jf2048**
Ubuntu 20.10 is EOL: https://lists.ubuntu.com/archives/ubuntu-announce/2021-July/000270.html

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You meant 20.10 I hope. :scream:

**Comment by jf2048** [comment]
Yes, sorry typo :)

**Comment by bilelmoussaoui** [comment]
> Ubuntu 20.10 is EOL: https://lists.ubuntu.com/archives/ubuntu-announce/2021-July/000270.html

See #484, we should switch to using Fedora here.

**Comment by jf2048** [comment]
I just noticed that in the gtk4-rs container, let's close this and make another one using fedora

**Pull request closed without merging**
