### PR TITLE
glib: Add new object constructor for constructing an object with default property values

### PR DESCRIPTION
**Pull request by sdroege**
Nicer than writing `Object::new(&[])`.

Also optimize the object builder a bit.

### CODE REVIEW

**Comment by pbor** [comment]
Is this really that common that we need to optimize for it? Usually this is wrapped into a `new()` method for the concrete object.

Maybe we should `impl Default` and have it call `Object::new(T::static_type(), &[])`?

`new_default_with_type` seems even less common and if one is writing some kind of factory object they can stick to passing in `&[]`

**Comment by sdroege** [comment]
> Is this really that common that we need to optimize for it? Usually this is wrapped into a `new()` method for the concrete object.

All the `Default` impls are calling `new(&[])` currently, and I know that I'm having to write this quite often for subclasses. So at least for me it's going to save some annoying typing :)

> Maybe we should `impl Default` and have it call `Object::new(T::static_type(), &[])`?

This would be called from the `impl Default`, yes.

**Comment by sdroege** [comment]
Also note that I'm working on deprecating `::new()` and `::with_type()` and `::with_values()` as those all unnecessarily copy the property values twice.

**Comment by pbor** [comment]
Ah ok then, if the redundancy is removed the other way round then ok

**Comment by pbor** [comment]
Initable and AsyncInitable will need the same updates for consistency

**Comment by sdroege** [comment]
> Initable and AsyncInitable will need the same updates for consistency

Yeah they should also get builders. That API became quite bitrotten already...

**Comment by sdroege** [comment]
As discussed, names are as good as it can be for this release and for the release afterwards (after having deprecated `new()` for this release), we can switch over from `new_default()` to `new()`. There's also an issue so we don't forget.

I'll finish the (async) initable changes and then merge this.

**Pull request merged**
