### PR TITLE
glib: Implement enum paramspec builder variant that builds the defaul…

### PR DESCRIPTION
**Pull request by sdroege**
…t value automatically

Fixes https://github.com/gtk-rs/gtk-rs-core/issues/831

### CODE REVIEW

**Comment by sdroege** [comment]
@bilelmoussaoui @pbor What do you think?

**Comment by pbor** [comment]
It still seems backward to me: if I have a enum with `Default` I just want to call `.build()` if I do not have a default, I can specify with it `with_default`.

What about adding a `with_default()` method that returns a new type `ParamSpecEnumBuilderWithDefault` which has a `build()` method and instead require `Default` for the `build()` method on `ParamSpecEnumBuilder`

**Comment by sdroege** [comment]
How is that different from this API other than `build_with_default()` vs. `with_default()` as the function name?

**Comment by pbor** [comment]
> How is that different from this API other than `build_with_default()` vs. `with_default()` as the function name?

Unless I misunderstood the PR, in your patch you use `build_with_default()` for enums that implement `Default`. In my proposal you need to use `with_default()` for enums that do *not* impl Default or if you want to force a different default value

**Comment by sdroege** [comment]
Ah I see, so you want to have it the other way around. I think that makes more sense actually, yes.

**Comment by sdroege** [comment]
Done that now.

**Review by pbor — APPROVED** [review]

**Pull request merged**
