### PR TITLE
Use bool instead of gboolean in graphene for FFI

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/199

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
Should maybe make a bugfix release with this but that also needs a bugfix branch for gir then...

**Comment by GuillaumeGomez** [comment]
Well, I don't expect people to regenerate with gir on the released branches...

**Comment by GuillaumeGomez** [comment]
Well, I'm not sure it's strictly needed but doesn't hurt to have a "clean" code way in case we need it. Thanks for doing it!

**Pull request merged**
