### PR TITLE
0.14 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
@GuillaumeGomez What should we do about the CI? Needs newer Rust version because of cfg-expr but we don't really want to increase the MSRV for the stable release. Also will probably cause new clippy warnings because you wanted to run clippy with beta ;)

**Comment by GuillaumeGomez** [comment]
I guess we don't have the choice: we need to remove commits changing the MSRV...

**Comment by sdroege** [comment]
> I guess we don't have the choice: we need to remove commits changing the MSRV...

That's outside our control. We could add a `Cargo.lock` though.

**Comment by GuillaumeGomez** [comment]
Not a big fan of `.lock` files. What about using `crate = "=0.x.y"` for `cfg-expr`?

**Comment by sdroege** [comment]
> Not a big fan of `.lock` files. What about using `crate = "=0.x.y"` for `cfg-expr`?

That will break things for people using newer Rust and having newer cfg-expr in their dependency tree. How is that better than Cargo.lock? Seems worse in every aspect :) Cargo.toml also affects users, Cargo.lock only affects people building the gtk-rs-core repository directly (and not as a dependency).

**Comment by cgwalters** [comment]
I hit the cfg-expr bit and dug into it a little and AFAICS the only thing was the new `Some(a | b)` bits in https://github.com/EmbarkStudios/cfg-expr/commit/7f856d7dec36943fbc0cc1f8310750d59b434137 which seems trivial to undo and I can't imagine would be a burden to carry for them.  Let's just put together the argument to do so in a PR?

**Comment by cgwalters** [comment]
https://github.com/EmbarkStudios/cfg-expr/pull/31

**Comment by GuillaumeGomez** [comment]
Should be fixed now.

**Comment by sdroege** [comment]
@GuillaumeGomez Can you do the same fix for the other unconnected test crate?

**Comment by GuillaumeGomez** [comment]
Sure!

**Comment by GuillaumeGomez** [comment]
Fixed as well, merging.

**Pull request merged**
