### PR TITLE
0.16 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Gah, we have new clippy warnings because beta updated behind our backs again.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
So I guess the master branch will have to fix clippy lints too. Better backport them once merged in the master branch too.

**Comment by sdroege** [comment]
That was my plan, yes. Someone will have to spend some time on fixing them first :)

**Comment by GuillaumeGomez** [comment]
Doing it then.

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
