### PR TITLE
Add minimal crate info

### PR DESCRIPTION
**Pull request by sophie-h**
Also adds minimum required version of the library to every crate doc.

### CODE REVIEW

**Comment by sophie-h** [comment]
Will do for gtk3/4 after review

**Comment by GuillaumeGomez** [comment]
That sounds quite complicated to maintain... Could we use `#[doc = include_str!("version.md")]` instead for the line containing the version?

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
> That sounds quite complicated to maintain... Could we use `#[doc = include_str!("version.md")]` instead for the line containing the version?

And where would this `version.md` come from? :)

**Comment by sophie-h** [comment]
> And where would this `version.md` come from? :)

That would have to be gir's task I guess?

**Comment by bilelmoussaoui** [comment]
> That sounds quite complicated to maintain... Could we use `#[doc = include_str!("version.md")]` instead for the line containing the version?

We had to maintain it as part of a README/ (website but not really because it was outdated)

**Comment by sophie-h** [comment]
Still it's something that gir knows. Can gir just dump a `library_version.md` in `src`?

**Comment by GuillaumeGomez** [comment]
> Still it's something that gir knows. Can gir just dump a `library_version.md` in `src`?

Good idea! Just need to check if `#[doc = include_str!()]` is stable or not first.

**Comment by GuillaumeGomez** [comment]
Unfortunately it's not stable yet: https://github.com/rust-lang/rust/pull/83366 (it'll be part of 1.54).

**Comment by sophie-h** [comment]
`#![cfg_attr(feature = "dox", doc = include_str!("version.md"))]` works for me

**Comment by sophie-h** [comment]
Ah, only on nightly :facepalm:

**Comment by sophie-h** [comment]
Merge as is for now?

**Comment by GuillaumeGomez** [comment]
You were about to make a revolution in how I saw versions in rust, too bad haha. That would have been super cool if it worked though.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Yes, thanks for doing this! Can you open an issue so we can update how we handle this once 1.54 is out please?

**Pull request merged**
