### PR TITLE
glib: implement ToGlibPtr<*mut _> for boxed types

### PR DESCRIPTION
**Pull request by pbor**

### CODE REVIEW

**Comment by pbor** [comment]
Same as https://github.com/gtk-rs/gtk-rs-core/pull/890 but with the requested changes

**Comment by sdroege** [comment]
Now "only" need to fix the usage everywhere :)

**Comment by pbor** [comment]
> Now "only" need to fix the usage everywhere :)

Fixed (I hope) but please double check that using `as_ptr()` instead of `to_glib_none().0` is legit

**Comment by sdroege** [comment]
> Fixed (I hope) but please double check that using `as_ptr()` instead of `to_glib_none().0` is legit

They're doing the same thing, yes.

**Review by sdroege — APPROVED** [review]

**Pull request merged**
