### PR TITLE
stable docs: add pango-sys to search index

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
How come it wasn't in the search index in the first place? Also, it's generally a bad idea to insert things manually like that, rustdoc is modifying more than this file when generating docs.

**Comment by bilelmoussaoui** [comment]
Because i copied the docs manually from https://github.com/gtk-rs/docs and removed the gtk specific crates from the search index and i mistakenly removed pango-sys

**Comment by GuillaumeGomez** [comment]
😨 

Well, let's merge and hope for the best.

**Comment by bilelmoussaoui** [comment]
> fearful
> 
> Well, let's merge and hope for the best.

It works just fine.

**Pull request merged**
