### PR TITLE
impl `ToValue`, `FromValue` for char

### PR DESCRIPTION
**Pull request by ranfdev**
solves #576 and also lets me correctly handle `ParamSpecUnichar` in #494

### CODE REVIEW

**Comment by sdroege** [comment]
Can you rebase on latest master so the CI passes?

**Review by sdroege — APPROVED** [review]
Looks good to me otherwise, thanks!

**Comment by sdroege** [comment]
Rebased

**Comment by sdroege** [comment]
And ran `cargo fmt`.

**Comment by ranfdev** [comment]
Nice! I don't have access to a PC right now... Reviewing from the phone.
Everything seems good 👍

**Pull request merged**
