### PR TITLE
Fix some typo and warnings

### PR DESCRIPTION
**Pull request by remilauzier**

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Review by sdroege — CHANGES_REQUESTED** [review]
Actually I missed a part. Please don't update the `gir` / `gir-files` submodules :)

Also for the futures such commits would be easier to review if you split them up a bit by category but that's OK this time.

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Can you run this through `cargo fmt` once? Thanks!

**Comment by sdroege** [comment]
> Can you run this through `cargo fmt` once? Thanks!

Did that now :)

**Comment by sdroege** [comment]
@GuillaumeGomez Should we get this into 0.14? Seems potentially useful for the docs fixes.

But also: why didn't clippy in the CI complain about various of these things?

**Comment by GuillaumeGomez** [comment]
We have another issue that I'm waiting to be fixed before making a small release.

**Comment by sdroege** [comment]
Yeah but should I cherry pick and create a PR?

**Comment by GuillaumeGomez** [comment]
Yes please! :)

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/170

**Comment by remilauzier** [comment]
> @GuillaumeGomez Should we get this into 0.14? Seems potentially useful for the docs fixes.
> 
> But also: why didn't clippy in the CI complain about various of these things?

I used rust nightly to find some of these and the other is intellij idea that find them, like deprecated std::u32::max.

**Comment by GuillaumeGomez** [comment]
Maybe we should run these checks on nightly as well then?

**Comment by sdroege** [comment]
No, nightly clippy changes too often. Right now we only need to update things every 6 weeks, with nightly clippy we might have to update things every night :)

**Comment by GuillaumeGomez** [comment]
Maybe beta then? That'd give us a 6 weeks head start.

**Comment by sdroege** [comment]
Works for me

**Comment by GuillaumeGomez** [comment]
Ok, gonna send a PR shortly.

**Pull request merged**
