### PR TITLE
glib-macros: add proc_macro_error attribute to clone

### LINKED ISSUE #124: Add #[proc_macro_error] to clone! macro
So it reports errors correctly

```
error: proc macro panicked
  --> src/application/imp.rs:61:13
   |
61 | /             clone!(@weak app as app => move |_,_| {
62 | |                 let preferences = PreferencesWindow::new();
63 | |                 preferences.set_transient_for(Some(&app.main_window()));
64 | |                 preferences.set_window(&app.main_window());
65 | |                 preferences.show();
66 | |             })
   | |______________^
   |
   = help: message: proc-macro-error API cannot be used outside of `entry_point` invocation, perhaps you forgot to annotate your #[proc_macro] function with `#[proc_macro_error]

```

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Should hopefully fix #124

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please add a test for the error message (in `./glib/clone_tests/clone_compilation_errors.py`).

**Comment by sdroege** [comment]
What error message? For a test that this doesn't regress again we have the book tests (once the PR is merged).

**Comment by GuillaumeGomez** [comment]
Just double-checked and indeed, just a cryptic error. Really strange it didn't appear before... Thanks!

**Comment by bilelmoussaoui** [comment]
> What error message? For a test that this doesn't regress again we have the book tests (once the PR is merged).

Not only the book, the examples fails to build as well

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
