### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by GuillaumeGomez — DISMISSED** [review]

**Comment by GuillaumeGomez** [comment]
Looks like Windows CI failed. :laughing:

**Comment by sdroege** [comment]
> Looks like Windows CI failed. laughing

That's what I'm fixing here step by step. It was failing since quite a while already it seems.

**Comment by GuillaumeGomez** [comment]
Please ping me once ready then. :)

**Comment by sdroege** [comment]
Well, it's good now. No more changes were needed :)

**Pull request merged**
